/**
 * Shared tag taxonomy constants.
 * Used by both build-content-index.ts and validate-content.ts.
 */

// ---- Valid Tag Slugs (controlled vocabulary) ----

export const VALID_TAG_SLUGS = new Set([
  // Technique
  'power-chords', 'barre-chords', 'open-chords', 'alternate-picking',
  'hybrid-picking', 'sweep-picking', 'fingerpicking', 'bending', 'vibrato',
  'hammer-on', 'pull-off', 'legato', 'tapping', 'slide', 'palm-muting',
  'string-skipping', 'strumming', 'arpeggios', 'percussive', 'call-response',
  'improvisation', 'syncopation', 'motif-development', 'phrasing', 'target-notes',
  // Theory
  'major-key', 'minor-key', 'pentatonic', 'blues-scale', 'modal', 'intervals',
  'chord-theory', 'chord-progressions', 'voice-leading', 'song-structure',
  'rhythm-theory', 'scale-theory', 'harmonic-minor', 'roman-numerals',
  'secondary-dominants', 'substitutions', 'modal-interchange',
  // Gear
  'electric-guitar', 'acoustic-guitar', 'bass-guitar', 'classical-guitar',
  'tube-amp', 'solid-state-amp', 'modeling-amp', 'overdrive', 'distortion',
  'fuzz', 'delay', 'reverb', 'chorus', 'wah', 'compressor', 'tremolo',
  'recording', 'accessories', 'microphones', 'audio-interface', 'daw',
  'monitors', 'preamps',
  // Genre
  'classic-rock', 'blues', 'metal', 'punk', 'jazz', 'country', 'folk',
  'funk', 'pop', 'reggae', 'latin', 'fingerstyle',
  // Difficulty
  'beginner', 'intermediate', 'advanced', 'expert',
  // Instrument
  'rhythm-guitar', 'lead-guitar',
  // Content-type
  'warmup', 'exercise', 'song-analysis', 'lesson',
]);

// ---- Tag Normalization ----
// Maps existing descriptive tags to taxonomy slugs

export const TAG_NORMALIZATION: Record<string, string | null> = {
  // Chord descriptive tags
  'foundation of harmony': 'chord-theory',
  'bright & stable': 'major-key',
  'universal appeal': null,          // skip, not useful
  'essential building block': 'chord-theory',
  'dark & emotional': 'minor-key',
  'moody & mysterious': 'minor-key',
  'melancholy & depth': 'minor-key',
  'tension & resolution': 'chord-theory',
  'jazz & blues essential': 'jazz',
  'bright & jazzy': 'jazz',
  'sophisticated & warm': 'jazz',
  'moody & smooth': 'jazz',
  'open & ambiguous': 'chord-theory',
  'neither major nor minor': 'chord-theory',
  'unstable & transitional': 'chord-theory',
  'diminished & mysterious': 'chord-theory',
  'symmetrical harmony': 'chord-theory',
  'dissonance & tension': 'chord-theory',
  'leading tone function': 'chord-theory',
  'sharp & bright': 'chord-theory',
  'whole-tone character': 'chord-theory',
  'augmented symmetry': 'chord-theory',
  'rich & colorful': 'chord-theory',
  'beyond triads': 'chord-theory',
  'modern harmony': 'chord-theory',
  'jazz essential': 'jazz',
  // Interval tags
  'perfect consonance': 'intervals',
  'harmonic foundation': 'intervals',
  'playing in unison': 'intervals',
  'root note reference': 'intervals',
  'minor second': 'intervals',
  'sharp dissonance': 'intervals',
  'chromatic neighbor': 'intervals',
  'minor chord foundation': 'minor-key',
  '3 semitones': null,
  '4 semitones': null,
  '5 semitones': null,
  '6 semitones': null,
  '7 semitones': null,
  '8 semitones': null,
  '9 semitones': null,
  '10 semitones': null,
  '11 semitones': null,
  '12 semitones': null,
  'major chord foundation': 'major-key',
  'bright & happy': 'major-key',
  'consonant': 'intervals',
  'darker consonance': 'minor-key',
  'power chords': 'power-chords',
  'strong consonance': 'intervals',
  'tritone substitute': 'intervals',
  'the devil\'s interval': 'intervals',
  'enharmonic pair': 'intervals',
  'sweet & warm': 'intervals',
  'natural minor': 'minor-key',
  'full octave': 'intervals',
  'perfect interval': 'intervals',
  '1 semitone': null,
  '2 semitones': null,
  // Mode tags (skip formula patterns, normalize meaningful ones)
  'modern & jazzy': 'jazz',
  'dark & exotic': 'modal',
  'bright & uplifting': 'modal',
  'darkest mode': 'modal',
  'standard major': 'major-key',
  'dominant flavor': 'modal',
  'blues connection': 'blues',
  'natural minor sound': 'minor-key',
  // Progression tags
  'tonic-subdominant-dominant': 'chord-progressions',
  '3 chords': null,
  'strong resolution': 'chord-progressions',
  'universal pattern': 'chord-progressions',
  'turnaround': 'chord-progressions',
  '12-bar form': 'blues',
  'the most popular': null,
  '4-chord magic': null,
  // Scale tags (already keyword-style, mostly valid)
  'essential': null,
  'diatonic': 'scale-theory',
  'foundation': null,
  'ionian': 'modal',
  'scales': 'scale-theory',
  'theory': null,
  'beginner-friendly': 'beginner',

  // Comprehensive normalization for catalog tags
  '#4 (raised 4th)': 'modal',
  '0 semitones': null,
  '12-bar': 'blues',
  '12-measure form': 'blues',
  '12-bar-blues': 'blues',
  '12-string': 'acoustic-guitar',
  '2-chord-song': 'chord-progressions',
  '2:1 frequency ratio': null,
  '3-chord-song': 'chord-progressions',
  '4 chords': 'chord-progressions',
  '7 notes': null,
  '80s-rock': 'classic-rock',
  '90s': 'classic-rock',
  'acoustic': 'acoustic-guitar',
  'acoustic favorite': 'acoustic-guitar',
  'add9-chords': 'open-chords',
  'advanced harmony': 'chord-theory',
  'advanced jazz': 'jazz',
  'advanced voicings': 'chord-theory',
  'aeolian': 'minor-key',
  'alternative': 'classic-rock',
  'alternative-metal': 'metal',
  'alternative-rock': 'classic-rock',
  'ambiguous sound': 'chord-theory',
  'andy-summers': null,
  'anthem': 'classic-rock',
  'arena-rock': 'classic-rock',
  'augmented': 'chord-theory',
  'australian rock': 'classic-rock',
  'bass movement': 'voice-leading',
  'beginner friendly': 'beginner',
  'beginner-intermediate': 'intermediate',
  'beginner-riff': 'beginner',
  'black-sabbath': null,
  'blues rock': 'blues',
  'blues standard': 'blues',
  'blues-rock': 'blues',
  'bluesy sound': 'blues',
  'bob-dylan': null,
  'bossa nova': 'jazz',
  'boston': null,
  'britpop': 'classic-rock',
  'bvii': 'chord-progressions',
  'cadence': 'chord-progressions',
  'campfire-song': 'acoustic-guitar',
  'chorus-effect': 'chorus',
  'chromatic': 'scale-theory',
  'chromatic foundation': 'intervals',
  'chromatic movement': 'voice-leading',
  'chromatic passing': 'voice-leading',
  'chuck berry': null,
  'circle of fifths': 'chord-progressions',
  'classic': null,
  'classic rock': 'classic-rock',
  'classical': 'fingerstyle',
  'clean-to-heavy': 'distortion',
  'clean-tone': 'electric-guitar',
  'color tones': 'chord-theory',
  'colorful extensions': 'chord-theory',
  'comping': 'rhythm-guitar',
  'complex-arrangement': 'song-structure',
  'complex-rhythm': 'rhythm-theory',
  'country-rock': 'country',
  'cream': null,
  'creative color': 'chord-theory',
  'dark tension': 'minor-key',
  'demands resolution': 'intervals',
  'devil\'s interval': 'intervals',
  'diminished': 'chord-theory',
  'dissonant': 'chord-theory',
  'distortion-friendly': 'distortion',
  'dominant': 'chord-theory',
  'dominant & bluesy': 'modal',
  'dominant function': 'intervals',
  'dominant-tonic': 'chord-progressions',
  'doo-wop': 'pop',
  'dorian': 'modal',
  'dorian-mode': 'modal',
  'double stops': 'lead-guitar',
  'dramatic sound': 'chord-theory',
  'dreamy & floating': 'modal',
  'dreamy harmony': 'chord-theory',
  'driving-rhythm': 'rhythm-guitar',
  'drop-d': 'power-chords',
  'dual-guitar': 'lead-guitar',
  'dual-harmony': 'lead-guitar',
  'dynamic-build': 'song-structure',
  'dynamic-contrast': 'phrasing',
  'dynamics': 'phrasing',
  'electric-blues': 'blues',
  'elegant tension': 'intervals',
  'elvis': null,
  'emotional & dark': 'minor-key',
  'emotional cycle': 'chord-progressions',
  'emotional depth': 'minor-key',
  'emotional journey': 'chord-progressions',
  'eric-clapton': null,
  'essential chord type': 'chord-theory',
  'exotic': 'modal',
  'exotic & spanish': 'modal',
  'expressive': null,
  'expressive harmony': 'chord-theory',
  'extended harmony': 'chord-theory',
  'fast-picking': 'alternate-picking',
  'fast-tempo': 'alternate-picking',
  'female-artist': null,
  'film-score': null,
  'first-song': 'beginner',
  'flamenco': 'latin',
  'folk-rock': 'folk',
  'foundation of music': 'intervals',
  'foundation of pitch': 'intervals',
  'funk essential': 'funk',
  'fundamental': 'scale-theory',
  'fusion': 'jazz',
  'garage-rock': 'punk',
  'genre-defining': null,
  'glam-metal': 'metal',
  'gospel': 'pop',
  'green-day': null,
  'grunge': 'classic-rock',
  'guitar tuning foundation': 'intervals',
  'guitar-intro': 'lead-guitar',
  'guitar-riff': 'lead-guitar',
  'guitar-solo': 'lead-guitar',
  'guitar-solos': 'lead-guitar',
  'h-w-w-h-w-w-w': null,
  'h-w-w-w-h-w-w': null,
  'hard rock': 'classic-rock',
  'hard-rock': 'classic-rock',
  'harmonic driver': 'intervals',
  'harmonic reinforcement': 'intervals',
  'harmonics': 'fingerstyle',
  'heavy-metal': 'metal',
  'hendrix chord': 'electric-guitar',
  'i-iv-v foundation': 'chord-progressions',
  'iconic riff': 'lead-guitar',
  'iconic-intro': 'lead-guitar',
  'iconic-riff': 'lead-guitar',
  'ii in minor': 'chord-theory',
  'impressionist': null,
  'indie-pop': 'pop',
  'indie-rock': 'classic-rock',
  'instrumental': 'lead-guitar',
  'inversions': 'chord-theory',
  'jazz & classical': 'jazz',
  'jazz color': 'jazz',
  'jazz colors': 'jazz',
  'jazz foundation': 'jazz',
  'jazz harmony': 'jazz',
  'jazz standard': 'jazz',
  'jazz-chords': 'jazz',
  'jazz-fusion': 'jazz',
  'joan jett': null,
  'kiss': null,
  'latin-rock': 'latin',
  'led-zeppelin': null,
  'locrian': 'modal',
  'lush sound': 'chord-theory',
  'lydian': 'modal',
  'major': 'major-key',
  'major 3rd inversion': 'intervals',
  'major with ♭7': 'modal',
  'maximum dissonance': 'intervals',
  'maximum tension': 'intervals',
  'melancholic beauty': 'minor-key',
  'melodic-minor': 'minor-key',
  'minimal': null,
  'minor': 'minor-key',
  'minor 3rd inversion': 'intervals',
  'minor color': 'minor-key',
  'minor start': 'minor-key',
  'minor with ♮6': 'modal',
  'minor-family': 'minor-key',
  'mixolydian': 'modal',
  'mixolydian-mode': 'modal',
  'modal borrowing': 'modal-interchange',
  'mode': 'modal',
  'modern pop staple': 'pop',
  'modern-rock': 'classic-rock',
  'moody': 'minor-key',
  'mysterious sound': 'minor-key',
  'natural movement': 'intervals',
  'natural scale': 'major-key',
  'natural-minor': 'minor-key',
  'new-wave': 'pop',
  'odd-time': 'rhythm-theory',
  'open harmony': 'open-chords',
  'open voicings': 'open-chords',
  'outlaw-country': 'country',
  'perfect unity': 'intervals',
  'phrygian': 'modal',
  'plagal': 'chord-progressions',
  'polyrhythm': 'rhythm-theory',
  'pop classic': 'pop',
  'pop essential': 'pop',
  'pop foundation': 'pop',
  'pop-rock': 'pop',
  'power-ballad': 'classic-rock',
  'pre-dominant': 'chord-progressions',
  'prog-metal': 'metal',
  'prog-rock': 'classic-rock',
  'progressive': 'classic-rock',
  'progressive-rock': 'classic-rock',
  'proto-punk': 'punk',
  'psychedelic-rock': 'classic-rock',
  'pub rock': 'classic-rock',
  'punk-rock': 'punk',
  'queen': null,
  'r&b': 'pop',
  'r-and-b': 'pop',
  'resolution': 'chord-progressions',
  'rhythm': 'rhythm-guitar',
  'rich & complex': 'intervals',
  'rich harmony': 'chord-theory',
  'rock': 'classic-rock',
  'rock anthem': 'classic-rock',
  'rock and roll': 'classic-rock',
  'rock-and-roll': 'classic-rock',
  'rock essential': 'classic-rock',
  'rockabilly': 'classic-rock',
  'rolling-stones': null,
  'safe': null,
  'scale foundation': 'scale-theory',
  'sequential fifths': 'chord-progressions',
  'shuffle': 'blues',
  'simple-chords': 'open-chords',
  'ska': 'reggae',
  'slide-guitar': 'slide',
  'smooth dissonance': 'intervals',
  'smooth sound': 'chord-theory',
  'smooth transitions': 'voice-leading',
  'smooth voice leading': 'voice-leading',
  'soft-rock': 'classic-rock',
  'sophisticated': null,
  'sophisticated voicings': 'chord-theory',
  'soul': 'pop',
  'soulful harmony': 'chord-theory',
  'southern rock': 'classic-rock',
  'southern-rock': 'classic-rock',
  'subdominant': 'chord-progressions',
  'sublime': null,
  'supertonic-dominant-tonic': 'chord-progressions',
  'sus4 chords': 'chord-theory',
  'sweet & romantic': 'intervals',
  'swing': 'jazz',
  'symmetric': 'scale-theory',
  'synth-rock': 'classic-rock',
  'talk-box': 'accessories',
  'technical': 'exercise',
  'tension': 'chord-theory',
  'tension & release': 'chord-theory',
  'tension builder': 'chord-theory',
  'the-beatles': null,
  'the-clash': null,
  'the-kinks': null,
  'the-police': null,
  'tom-petty': null,
  'tonic-dominant-relative minor-subdominant': 'chord-progressions',
  'two-chord': 'chord-progressions',
  'two-note': 'power-chords',
  'unstable & tense': 'modal',
  'van-morrison': null,
  'versatile': null,
  'versatile voicings': 'chord-theory',
  'vintage tone': 'tube-amp',
  'virtuoso': 'advanced',
  'voice leading': 'voice-leading',
  'w-h-w-w-h-w-w': null,
  'w-h-w-w-w-h-w': null,
  'w-w-h-w-w-h-w': null,
  'w-w-h-w-w-w-h': null,
  'w-w-w-h-w-w-h': null,
  'wah-pedal': 'wah',
  'waltz': 'rhythm-theory',
  'warm harmony': 'intervals',
  'warm-up': 'warmup',
  'whole step': 'intervals',
  'whole-tone': 'scale-theory',
  '♭2 & ♭5': 'modal',
  '♭2 (flat 2nd)': 'modal',
  '♭3, ♭6, ♭7': 'modal',
};
