AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket for musicscene.com.au (Sydney)

Parameters:
  DomainName:
    Type: String
    Default: musicscene.com.au

Resources:
  MusicSceneBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  BucketName:
    Description: The name of the S3 bucket created
    Value: !Ref MusicSceneBucket

  BucketRegion:
    Description: The region where the bucket lives
    Value: !Ref AWS::Region

  BucketEndpoint:
    Description: The REST endpoint for the bucket
    Value: !GetAtt MusicSceneBucket.DomainName
