AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Full static‑site infra for musicscene.com.au:
  • S3 website bucket
  • Public-read policy
  • Route 53 hosted zone
  • ACM certificate (DNS validation)
  • CloudFront + OAI + PriceClass_200
  • Route 53 A‑alias record

Parameters:
  DomainName:
    Type: String
    Default: musicscene.com.au
    Description: Your domain (and S3 bucket name)

Resources:

  ### S3 Bucket & Policy ###
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref DomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: S3Bucket
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - '/*'

  ### Route 53 Hosted Zone ###
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  ### ACM Certificate (DNS) ###
  Certificate:
    Type: AWS::CertificateManager::Certificate
    DependsOn: HostedZone
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone

  ### CloudFront Origin Access Identity ###
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${DomainName}"

  ### CloudFront Distribution ###
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - BucketPolicy
      - CloudFrontOAI
      - Certificate
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_200
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.RegionalDomainName   # <-- proper REST endpoint
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET","HEAD"]
          CachedMethods: ["GET","HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref DomainName
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html

  ### Route 53 A‑Alias to CloudFront ###
  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket

  WebsiteEndpoint:
    Description: S3 website URL (http)
    Value: !GetAtt S3Bucket.WebsiteURL

  RestEndpoint:
    Description: S3 REST endpoint (https)
    Value: !GetAtt S3Bucket.RegionalDomainName

  DistributionDomain:
    Description: CloudFront domain (https)
    Value: !GetAtt CloudFrontDistribution.DomainName

  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution

  HostedZoneId:
    Description: Route53 Hosted Zone ID
    Value: !Ref HostedZone

  CertificateArn:
    Description: ACM Certificate ARN
    Value: !Ref Certificate
