AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Static‑site stack for musicscene.com.au:
  • Route 53 Hosted Zone
  • S3 bucket (website hosting, public)
  • CloudFront distribution (PriceClass_200)
  • DNS A‑alias record

Parameters:
  DomainName:
    Type: String
    Default: musicscene.com.au
    Description: The domain to host (must match your registrar)

Resources:

  # 1) Route 53 Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  # Create ACM Certificate
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone

  # Replace OAI with OAC
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # 5) CloudFront Distribution (waits for bucket & policy & OAI)
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - WebsiteBucket
      - WebsiteBucketPolicy
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !ImportValue bucket-RegionalDomainName
            OriginAccessControlId: !GetAtt CloudFrontOAC.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ['GET','HEAD']
          CachedMethods: ['GET','HEAD']
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Aliases:
          - !Ref DomainName
        ResponseHeadersPolicy:
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy

  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${AWS::StackName}-security-headers'
        SecurityHeadersConfig:
          ContentSecurityPolicy:
            Override: true
            ContentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
          StrictTransportSecurity:
            Override: true
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Preload: true
          XSSProtection:
            Override: true
            Protection: true
            ModeBlock: true
          ReferrerPolicy:
            Override: true
            ReferrerPolicy: strict-origin-when-cross-origin

  # 6) DNS A‑alias record in the new hosted zone
  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: WebsiteDistribution
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront global zone ID

Outputs:
  HostedZoneId:
    Description: The Route 53 Hosted Zone ID
    Value: !Ref HostedZone

  CloudFrontURL:
    Description: CloudFront domain (https)
    Value: !GetAtt WebsiteDistribution.DomainName
