name: Deploy MusicScene Site

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Build & Export Next.js
        run: |
          npm install
          npm run build
          npm run export

      - name: Sync to S3
        run: |
           aws s3 sync ./out s3://musicscene --delete

      - name: Invalidate CloudFront Cache
        env:
          DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          if [ -z "$DIST_ID" ]; then
            echo "❌ No CloudFront distribution ID provided—skipping invalidation"
            exit 0
          fi

          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths '/*'
          echo "Invalidated CloudFront cache for distribution ID: $DIST_ID"
          echo "Deployment complete!"		
